#define TOU_BASE_VPIN 800
HAL(EXIOExpander, TOU_BASE_VPIN, 18, 0x65)
#define HBL_BASE_VPIN 820
HAL(EXIOExpander, HBL_BASE_VPIN, 18, 0x66)
#define HBU_BASE_VPIN 840
HAL(EXIOExpander, HBU_BASE_VPIN, 18, 0x66)
// #define DFP_BASE_VPIN 10000
// HAL(DFPlayer, DFP_BASE_VPIN, 10, Serial1)


// Mega - CommandStation Pin Assignements
// see https://dcc-ex.com/reference/hardware/pin-vpin-allocations.html
ALIAS(PIN_FAN, 2)
// reserve : 22 use for I2C interrupts
ALIAS(SENS_IR_STREET_WEST, 23)
ALIAS(SENS_IR_STREET_MIDD, 24)
ALIAS(SENS_IR_STREET_EAST, 25)
ALIAS(SENS_IR_TUNNEL_WEST, 26)
// unusable : A4 SDA
// unusable : A5 SDA
ALIAS(SENS_IR_TUNNEL_EAST, 27)
ALIAS(SENS_IR_STAGING_WB, 28)
ALIAS(SENS_IR_STAGING_EB, 29)
// usable : D30-D49
// usable : A8-A15


// Nano Every - Touch Panel Pin Assignments
// unusable : D0 TX
// unusable : D1 RX
ALIAS(TOU_2_1, TOU_BASE_VPIN+0) // D2
ALIAS(TOU_2_2, TOU_BASE_VPIN+1) // D3
ALIAS(TOU_2_3, TOU_BASE_VPIN+2) // D4
ALIAS(TOU_2_4, TOU_BASE_VPIN+3) // D5
ALIAS(TOU_2_5, TOU_BASE_VPIN+4) // D6
ALIAS(TOU_2_6, TOU_BASE_VPIN+5) // D7
ALIAS(TOU_2_7, TOU_BASE_VPIN+6) // D8
ALIAS(TOU_2_8, TOU_BASE_VPIN+7) // D9
ALIAS(TOU_2_9, TOU_BASE_VPIN+8) // D10
// ALIAS(usable, TOU_BASE_VPIN+9) // D11
ALIAS(TOU_1_1, TOU_BASE_VPIN+10) // D12
// ALIAS(usable, TOU_BASE_VPIN+11) // D13 may be tied to the onboard LED
ALIAS(TOU_1_2, TOU_BASE_VPIN+12) // A0
ALIAS(TOU_1_3, TOU_BASE_VPIN+13) // A1
ALIAS(TOU_1_4, TOU_BASE_VPIN+14) // A2
ALIAS(TOU_1_5, TOU_BASE_VPIN+15) // A3
// unusable : A4 SDA
// unusable : A5 SDA
ALIAS(TOU_1_6, TOU_BASE_VPIN+16) // A6
ALIAS(SENS_HEAT, TOU_BASE_VPIN+17) // A7


// Nano Every - H-Bridge Lower Level Pin Assignments
// unusable : D0 TX
// unusable : D1 RX
ALIAS(HBL_1_1_A, HBL_BASE_VPIN+0) // D2
ALIAS(HBL_1_1_B, HBL_BASE_VPIN+1) // D3
ALIAS(HBL_1_1_E, HBL_BASE_VPIN+2) // D4
ALIAS(HBL_1_2_A, HBL_BASE_VPIN+3) // D5
ALIAS(HBL_1_2_B, HBL_BASE_VPIN+4) // D6
ALIAS(HBL_1_2_E, HBL_BASE_VPIN+5) // D7
ALIAS(HBL_1_3_A, HBL_BASE_VPIN+6) // D8
ALIAS(HBL_1_3_B, HBL_BASE_VPIN+7) // D9
ALIAS(HBL_1_3_E, HBL_BASE_VPIN+8) // D10
ALIAS(HBL_1_4_A, HBL_BASE_VPIN+9) // D11
ALIAS(HBL_1_4_B, HBL_BASE_VPIN+10) // D12
ALIAS(HBL_1_4_E, HBL_BASE_VPIN+11) // D13 may be tied to the onboard LED
ALIAS(HBL_1_5_A, HBL_BASE_VPIN+12) // A0
ALIAS(HBL_1_5_B, HBL_BASE_VPIN+13) // A1
ALIAS(HBL_1_5_E, HBL_BASE_VPIN+14) // A2
ALIAS(HBL_1_6_A, HBL_BASE_VPIN+15) // A3
// unusable : A4 SDA
// unusable : A5 SDA
ALIAS(HBL_1_6_B, HBL_BASE_VPIN+16) // A6
ALIAS(HBL_1_6_E, HBL_BASE_VPIN+17) // A7


// Nano Every - H-Bridge Upper Level Pin Assignments
// unusable : D0 TX
// unusable : D1 RX
ALIAS(HBU_2_1_A, HBU_BASE_VPIN+0) // D2
ALIAS(HBU_2_1_B, HBU_BASE_VPIN+1) // D3
ALIAS(HBU_2_1_E, HBU_BASE_VPIN+2) // D4
ALIAS(HBU_2_2_A, HBU_BASE_VPIN+3) // D5
ALIAS(HBU_2_2_B, HBU_BASE_VPIN+4) // D6
ALIAS(HBU_2_2_E, HBU_BASE_VPIN+5) // D7
ALIAS(HBU_2_3_A, HBU_BASE_VPIN+6) // D8
ALIAS(HBU_2_3_B, HBU_BASE_VPIN+7) // D9
ALIAS(HBU_2_3_E, HBU_BASE_VPIN+8) // D10
ALIAS(HBU_2_4_A, HBU_BASE_VPIN+9) // D11
ALIAS(HBU_2_4_B, HBU_BASE_VPIN+10) // D12
ALIAS(HBU_2_4_E, HBU_BASE_VPIN+11) // D13 may be tied to the onboard LED
ALIAS(HBU_2_5_A, HBU_BASE_VPIN+12) // A0
ALIAS(HBU_2_5_B, HBU_BASE_VPIN+13) // A1
ALIAS(HBU_2_5_E, HBU_BASE_VPIN+14) // A2
ALIAS(HBU_2_6_A, HBU_BASE_VPIN+15) // A3
// unusable : A4 SDA
// unusable : A5 SDA
ALIAS(HBU_2_6_B, HBU_BASE_VPIN+16) // A6
ALIAS(HBU_2_6_E, HBU_BASE_VPIN+17) // A7

// TOOD HBU_2_7 & 8 & 9

// TODO setup DFPlayer audio pins
