@startuml Power Distribution

!theme crt-amber
skinparam componentStyle rectangle

component [Wall Outlet] as wall
component [Laptop PSU] as psu
component [Buck Converter 9V] as buck9
component [Buck Converter 12V] as buck12
frame "CommandStation-EX" {
    component [Arduino\nMega] as mega
    component [Arduino\nMotor Shield rev3] as motor
    component [Makerfabs\nESP8266 WiFi Shield] as wifi
}
component [Arduino\nNano Every\n(x4)] as nano
component [IR Sensors\n(x5)] as ir
component [H Bridges\n(x9)] as h_bridges
component [Touch Toggles\n(x15)] as touch
component [Fan] as fan

wall --> psu : 120V AC
psu --> buck9 : 19.5V DC
psu --> buck12 : 19.5V DC

buck12 --> h_bridges : 12V DC
buck12 ---> motor : 12V DC

buck9 --> mega : 9V DC
buck9 --> nano : 9V DC

mega --> motor : 5V DC
motor --> wifi : 5V DC
mega --> fan : 5V DC

nano --> ir : 5V DC
nano --> touch : 5V DC

@enduml