@startuml Power Distribution

component [Wall Outlet] as wall
component [Laptop PSU] as psu
component [Buck Converter 8V] as buck8
component [Buck Converter 14V] as buck14
component "CommandStation-EX" {
    component [Mega] as mega
    component [Motor Shield] as motor
    component [WiFi Shield] as wifi
}
component [Nano Every (x4)] as nano
component [IR Sensors (x5)] as ir
component [H Bridges (x9)] as h_bridges
component [Touch Toggles (x15)] as touch
component [Fan] as fan

wall --> psu : 120V AC
psu --> buck8 : 19.5V DC
psu --> buck14 : 19.5V DC

buck14 --> h_bridges : 14V DC
buck14 ---> motor : 14V DC

buck8 --> mega : 8V DC
buck8 --> nano : 8V DC

mega --> motor : 5V DC
motor --> wifi : 5V DC
mega --> fan : 5V DC

nano --> ir : 5V DC
nano --> touch : 5V DC

@enduml